from datetime import datetime
from enum import Enum
from typing import Dict, Any, Optional
from pydantic import BaseModel, Field


class SignalAction(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class StrategyType(str, Enum):
    RSI = "RSI"
    MACD = "MACD"
    RSI_SUPPORT_RESISTANCE = "RSI_SUPPORT_RESISTANCE"
    CUSTOM = "CUSTOM"


class Signal(BaseModel):
    """Represents a trading signal generated by a strategy."""

    strategy: StrategyType
    symbol: str
    action: SignalAction
    confidence: float = Field(ge=0.0, le=1.0, default=1.0)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    indicators: Dict[str, Any] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        use_enum_values = True


class RSISignalData(BaseModel):
    """RSI-specific signal data."""

    rsi_value: float
    rsi_period: int = 14
    oversold_threshold: float = 30.0
    overbought_threshold: float = 70.0
    support_level: Optional[float] = None
    resistance_level: Optional[float] = None


class MACDSignalData(BaseModel):
    """MACD-specific signal data."""

    macd_line: float
    signal_line: float
    histogram: float
    prev_macd_line: float
    prev_signal_line: float
    prev_histogram: float
    crossover_detected: bool = False
    crossover_type: Optional[str] = None  # "BULLISH" or "BEARISH"


class SignalRequest(BaseModel):
    """Request to calculate a signal for a symbol."""

    symbol: str
    strategy: StrategyType
    parameters: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        use_enum_values = True


class SignalResponse(BaseModel):
    """Response containing the calculated signal."""

    success: bool
    signal: Optional[Signal] = None
    message: str = ""
    raw_data: Optional[Dict[str, Any]] = None
